### ISSUE TITLE
Executing visit method when rendering back buffer

### ISSUE THREAD

**Issue by sechaparroc** [VisualComputing/frames#1]
Hi @nakednous,

When we override the visit method of a Frame is to render something on the Front Buffer of the Scene, as Back Buffer must be used only by a Shape.

But the visit method of a frame (nevermind if it is a Shape or a Frame) is called when the Back Buffer is rendered.

The next example summarizes this issue, although apparently there's no bad behavior:

`    
   
    Scene scene;
    Frame frame, shape;

    public void settings() {
        size(800, 800, P3D);
    }

    public void setup() {
        scene = new Scene(this);
        scene.setRadius(1000);
        scene.fitBallInterpolation();
        frame = new Frame(scene) {
            @Override
            public void visit() {
                /*
                * It seems that we want to execute this code only when traversing scene to render frontBuffer.
                * Currently, it is executed when the method Scene._renderBackBuffer is executed.
                *
                * Disabling backBuffer isn't an option since it could be Frames and Shapes in the same Scene.
                * */
                System.out.println("Must entry here only after calling scene.traverse() explicitly");

                //Not sure if applying a transformation like this will induce errors:
                /*
                * push() and pop() manage the stack of frontBuffer
                * but what if this method is called when rendering backBuffer?
                * */
                pushMatrix();
                pushStyle();
                scene.applyTransformation(new Frame(new Vector(200,200)));
                scene.drawAxes(100);
                popStyle();
                popMatrix();
                pushStyle();
                fill(255, 0, 255);
                sphere(scene.radius() / 4);
                stroke(255, 255, 0);
                scene.drawShooterTarget(this);
                popStyle();
            }
        };
        frame.setRotation(Quaternion.random());
        shape = new Shape(scene, shape());
        shape.setRotation(Quaternion.random());
        shape.translate(275, 275, 275);
    }

    public void draw() {
        background(0);
        scene.drawAxes();
        scene.traverse();
    }

    @Override
    public void mouseMoved() {
        scene.track();
    }

    @Override
    public void mouseDragged() {
        if (mouseButton == LEFT)
            scene.spin();
        else if (mouseButton == RIGHT)
            scene.translate();
        else
            scene.zoom(mouseX - pmouseX);
    }

    PShape shape() {
        PShape fig = scene.is3D() ? createShape(BOX, 150) : createShape(RECT, 0, 0, 150, 150);
        fig.setStroke(255);
        fig.setFill(color(random(0, 255), random(0, 255), random(0, 255)));
        return fig;
    }
`

**Comment by nakednous** [comment]
@sechaparroc btw there's no need to call any matrix operation within your `visit()` such as `scene.applyTransformation()`, because `graph.traverse()` does it automatically.

**Comment by sechaparroc** [comment]
Ok @nakednous
Although `graph.traverse()` calls `scene.applyTransformation()`, in the example above I wanted to do an explicit call of this method because there could be cases in which `visit()` requires to use detached Frames that express local transformation and we don't want them to be part of the graph (e.g. when drawing a rotational constraint).
