### ISSUE TITLE
Problems with scene.track()

### ISSUE THREAD

**Issue by rvcristiand** [VisualComputing/frames#2]
Hi @nakednous and @sechaparroc

I made [this example](https://github.com/rvcristiand/Axes/blob/master/Axes.pde) to change the shape's color when is tracked. I see that, some time, when the mouse pointer is over a shape another shape is tracked.

Do you have any ideas ?

Thank u !

**Comment by nakednous** [comment]
Use Shape.setGraphics() only to draw stuff
