### ISSUE TITLE
Unusually behavior left/right handed scene.

### ISSUE THREAD

**Issue by rvcristiand** [VisualComputing/frames#3]
Hi @nakednous and @sechaparroc.

I made [this example](https://github.com/rvcristiand/Bubbles/blob/master/Bubbules.pde) where I draw many circles with a inner text. With double click changes between left and right handed scene's orientation. When the scene's orientation is left, the text, viewed from -Z, the text is _right_ oriented. But, when the scene's orientation is right, the text, viewed from -Z, the text is wrong oriented.

Then, it's necessary oriented the text in function of left/right handed or this's a issue.

Thank u !

**Comment by nakednous** [comment]
Use Shape.setGraphics() only to draw stuff
